### PR TITLE
Remove warning for Time#succ call; it's obselete

### PR DESCRIPTION
**Pull request by cored**

### CODE REVIEW

**Comment by dkubb** [comment]
Thanks for this, I didn't know `Time#succ` was being made obsolete.

**Comment by mbj** [comment]
@dkubb It was in the warnings for a long time. Thought you explicitly decided for that API for some reason.

**Comment by dkubb** [comment]
@mbj interestingly I never saw the warning before.

**Comment by mbj** [comment]
@dkubb I saw it in recent 1.9.3, when porting axiom to mutant.

**Pull request merged**
