### PR TITLE
Bump backports to 2.7.0

### PR DESCRIPTION
**Pull request by mbj**
Lets see what travis is saying. Devtools is well prepared, but might need to be updated also, in this case I'll add a commit to this PR.

### CODE REVIEW

**Comment by mbj** [comment]
Lol I totally forgot veritas does not use devtools ;)

**Comment by snusnu** [comment]
+1

trying to bundle veritas for `dm-relation-graph` and it fails

**Comment by mbj** [comment]
@snusnu Use my master branch for some minutes ;)

**Comment by dkubb** [comment]
@mbj thanks!

**Pull request merged**
